"""empty message

Revision ID: b42fa84725f7
Revises: 28f4bc7982a0
Create Date: 2020-03-05 19:22:09.896123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42fa84725f7'
down_revision = '28f4bc7982a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('picture', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Text(), nullable=False),
    sa.Column('free', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientName', sa.String(length=255), nullable=False),
    sa.Column('clientPhone', sa.String(length=255), nullable=False),
    sa.Column('clientWeekday', sa.String(length=3), nullable=False),
    sa.Column('clientTime', sa.Integer(), nullable=False),
    sa.Column('clientTeacherId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clientTeacherId'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('teachers')
    # ### end Alembic commands ###
